#!/bin/bash

# SketchyBar main configuration file

# Color Palette
source "$CONFIG_DIR/colors/catppuccin.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

# Bar Appearance
sketchybar --bar height=32 \
                 blur_radius=30 \
                 position=top \
                 sticky=off \
                 padding_left=10 \
                 padding_right=10 \
                 color=$BAR_COLOR \
                 corner_radius=9 \
                 y_offset=10 \
                 margin=10 \
                 shadow=off

# Default Item Settings
sketchybar --default icon.font="JetBrainsMono Nerd Font:Bold:17.0" \
                     icon.color=$WHITE \
                     label.font="JetBrainsMono Nerd Font:Bold:14.0" \
                     label.color=$WHITE \
                     padding_left=5 \
                     padding_right=5 \
                     label.padding_left=4 \
                     label.padding_right=10 \
                     icon.padding_left=10 \
                     icon.padding_right=4

# Left items
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/spaces.sh"

# Center items
source "$ITEM_DIR/media.sh"

# Right items
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/wifi.sh"

# Forcing all scripts to run the first time (never do this in a script)
sketchybar --update

echo "sketchybar configuration loaded"
